// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: encrypt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salt       int64  `protobuf:"varint,1,opt,name=salt,proto3" json:"salt,omitempty"`
	SessionId  int64  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId  int64  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SeqNo      int32  `protobuf:"varint,4,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	MessageLen int32  `protobuf:"varint,5,opt,name=message_len,json=messageLen,proto3" json:"message_len,omitempty"`
	Message    []byte `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EncryptMessage) Reset() {
	*x = EncryptMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encrypt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptMessage) ProtoMessage() {}

func (x *EncryptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_encrypt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptMessage.ProtoReflect.Descriptor instead.
func (*EncryptMessage) Descriptor() ([]byte, []int) {
	return file_encrypt_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptMessage) GetSalt() int64 {
	if x != nil {
		return x.Salt
	}
	return 0
}

func (x *EncryptMessage) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *EncryptMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *EncryptMessage) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *EncryptMessage) GetMessageLen() int32 {
	if x != nil {
		return x.MessageLen
	}
	return 0
}

func (x *EncryptMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_encrypt_proto protoreflect.FileDescriptor

var file_encrypt_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xb4, 0x01, 0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f,
	0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x71, 0x4e, 0x6f, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x65, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x6d, 0x73,
	0x5f, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_encrypt_proto_rawDescOnce sync.Once
	file_encrypt_proto_rawDescData = file_encrypt_proto_rawDesc
)

func file_encrypt_proto_rawDescGZIP() []byte {
	file_encrypt_proto_rawDescOnce.Do(func() {
		file_encrypt_proto_rawDescData = protoimpl.X.CompressGZIP(file_encrypt_proto_rawDescData)
	})
	return file_encrypt_proto_rawDescData
}

var file_encrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_encrypt_proto_goTypes = []interface{}{
	(*EncryptMessage)(nil), // 0: pb.EncryptMessage
}
var file_encrypt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encrypt_proto_init() }
func file_encrypt_proto_init() {
	if File_encrypt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encrypt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encrypt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encrypt_proto_goTypes,
		DependencyIndexes: file_encrypt_proto_depIdxs,
		MessageInfos:      file_encrypt_proto_msgTypes,
	}.Build()
	File_encrypt_proto = out.File
	file_encrypt_proto_rawDesc = nil
	file_encrypt_proto_goTypes = nil
	file_encrypt_proto_depIdxs = nil
}
