// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: rpc_service_encrypt.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EncryptedServiceClient is the client API for EncryptedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncryptedServiceClient interface {
	Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type encryptedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptedServiceClient(cc grpc.ClientConnInterface) EncryptedServiceClient {
	return &encryptedServiceClient{cc}
}

func (c *encryptedServiceClient) Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.EncryptedService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptedServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, "/pb.EncryptedService/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptedServiceServer is the server API for EncryptedService service.
// All implementations must embed UnimplementedEncryptedServiceServer
// for forward compatibility
type EncryptedServiceServer interface {
	Send(context.Context, *Message) (*Message, error)
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	mustEmbedUnimplementedEncryptedServiceServer()
}

// UnimplementedEncryptedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEncryptedServiceServer struct {
}

func (UnimplementedEncryptedServiceServer) Send(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedEncryptedServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedEncryptedServiceServer) mustEmbedUnimplementedEncryptedServiceServer() {}

// UnsafeEncryptedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptedServiceServer will
// result in compilation errors.
type UnsafeEncryptedServiceServer interface {
	mustEmbedUnimplementedEncryptedServiceServer()
}

func RegisterEncryptedServiceServer(s grpc.ServiceRegistrar, srv EncryptedServiceServer) {
	s.RegisterService(&EncryptedService_ServiceDesc, srv)
}

func _EncryptedService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptedServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EncryptedService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptedServiceServer).Send(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptedService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptedServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EncryptedService/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptedServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncryptedService_ServiceDesc is the grpc.ServiceDesc for EncryptedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncryptedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EncryptedService",
	HandlerType: (*EncryptedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _EncryptedService_Send_Handler,
		},
		{
			MethodName: "Handshake",
			Handler:    _EncryptedService_Handshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_service_encrypt.proto",
}
